drop table privilege_entity if exists cascade;
drop table role_privilege if exists cascade;
drop table role_entity if exists cascade;
drop table user_account_role if exists cascade;
drop table user_account_entity if exists cascade;

create table user_account_entity (
id varchar(255) not null,
email varchar(255) not null unique,
password varchar(255) not null,
enabled boolean not null,
account_non_expired boolean not null,
credentials_non_expired boolean not null,
account_non_locked boolean not null,
primary key (id)
);

create table role_entity (id bigint not null generated by default as identity, authority varchar(255), primary key (id));

create table privilege_entity (id bigint not null generated by default as identity, authority varchar(255), primary key (id));

create table user_account_role (role_id bigint not null, user_account_id varchar(255) not null, primary key (role_id, user_account_id));

create table role_privilege (role_id bigint not null, privilege_id bigint not null, primary key (role_id, privilege_id));

alter table if exists user_account_role add constraint FK4i98r94r1pscfn4vupyf5ivsr foreign key (role_id) references role_entity;
alter table if exists user_account_role add constraint FK4i98r94r1pscfn4vupyf5ivzq foreign key (user_account_id) references user_account_entity;

alter table if exists role_privilege add constraint FK63e4kry7o8rkut8m6v0p9p7ch foreign key (role_id) references role_entity;
alter table if exists role_privilege add constraint FK63e4kry7o8rkut8m6v0p9p8ch foreign key (privilege_id) references privilege_entity;