drop table privilege_entity if exists cascade;
drop table role_privilege if exists cascade;
drop table role_entity if exists cascade;
drop table user_account_role if exists cascade;
drop table user_account_entity if exists cascade;

create table user_account_entity (
id varchar(255) not null,
email varchar(255) not null unique,
password varchar(255) not null,
enabled boolean not null,
account_non_expired boolean not null,
credentials_non_expired boolean not null,
account_non_locked boolean not null,
primary key (id)
);

create table role_entity (id bigint not null generated by default as identity, authority varchar(255), primary key (id));

create table privilege_entity (id bigint not null generated by default as identity, authority varchar(255), primary key (id));

create table user_account_role (role_id bigint not null, user_account_id varchar(255) not null, primary key (role_id, user_account_id));

create table role_privilege (role_id bigint not null, privilege_id bigint not null, primary key (role_id, privilege_id));

alter table if exists user_account_role add constraint FK4i98r94r1pscfn4vupyf5ivsr foreign key (role_id) references role_entity;
alter table if exists user_account_role add constraint FK4i98r94r1pscfn4vupyf5ivzq foreign key (user_account_id) references user_account_entity;

alter table if exists role_privilege add constraint FK63e4kry7o8rkut8m6v0p9p7ch foreign key (role_id) references role_entity;
alter table if exists role_privilege add constraint FK63e4kry7o8rkut8m6v0p9p8ch foreign key (privilege_id) references privilege_entity;


drop table client_registration_entity_scopes if exists cascade;
drop table client_registration_entity if exists cascade;

create table client_registration_entity (
    id bigint not null,
    authorization_grant_type varbinary(255),
    authorization_uri varchar(255),
    client_authentication_method varbinary(255),
    client_id varchar(255) not null,
    client_name varchar(255),
    client_secret varchar(255) not null,
    issuer_uri varchar(255),
    jwk_set_uri varchar(255),
    redirect_uri varchar(255),
    registration_id varchar(255) not null unique,
    token_uri varchar(255),
    user_info_uri varchar(255),
    user_name_attribute_name varchar(255),
    primary key (id)
);

create table client_registration_entity_scopes (
    client_registration_entity_id bigint not null,
    scopes varchar(255)
);

alter table if exists client_registration_entity_scopes add constraint FK2fxwgeipi6ufr8ewv0wk12r14 foreign key (client_registration_entity_id) references client_registration_entity;
