spring:
  mail:
    host: localhost
    port: 2525

  h2:
    console:
      enabled: true
      path: /h2-console/

  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  resources:
    static-locations: file:src/main/resources/static/
    cache:
      period: 0

  devtools:
    restart:
      additional-paths: file:src/main/resources/static, file:src/main/resources/templates

logging:
  config:
    format: [ "%d{ HH:mm:ss.SSS } %-5p [ %c{ 1. } ] %s%e%n" ]
  level:
    dev.majidhajric: debug
    org.springframework: debug
    org.springframework.security: debug
    org.springframework.web: debug
    org.hibernate: debug

