server:
  port: 9000
  error:
    whitelabel:
      enabled: false
    path: /error

spring:
  application:
    name: authify

  sql:
    init:
      mode: always
      schema-locations: classpath:/sql/schema.sql
      data-locations: classpath:/sql/data.sql

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    defer-datasource-initialization: true

  hibernate:
    dialect: org.hibernate.dialect.H2Dialect
    ddl-auto: none

  h2:
    console:
      enabled: true
      path: /h2-console/

  profiles:
    active: dev

logging:
  config:
    format: [ "%d{ HH:mm:ss.SSS } %-5p [ %c{ 1. } ] %s%e%n" ]
  level:
    dev.majidhajric: debug
    org.springframework: info
    org.springframework.security: debug
    org.springframework.web: debug
    org.hibernate: debug

