server:
  port: 9000
  error:
    whitelabel:
      enabled: false
    path: /error

spring:
  application:
    name: oauth2-and-openid-server
  messages:
    basename: i18n/messages

  sql:
    init:
      mode: always
      schema-locations: classpath:/sql/schema.sql
      data-locations: classpath:/sql/data.sql

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    defer-datasource-initialization: true

  hibernate:
    dialect: org.hibernate.dialect.H2Dialect
    ddl-auto: create-drop

  mail:
    host: localhost
    port: 2525

  h2:
    console:
      enabled: false

  profiles:
    active: dev

logging:
  level:
    root: info

configuration:
  jwt:
    secret: secret
  remember-me: false
  email-as-username: true
  require-email-verification: false
  require-password-confirmation: true
  require-password-complexity: true
  disable-social-sign-in: false
  enable-multi-factor: true
  policy:
    length:
      min: 8
      max: 32
    uppercase-count: 1
    lowercase-count: 1
    digit-count: 1
    special-count: 1
