server:
  port: 9000

spring:
  application:
    name: authify

  security:
    user:
      name: user
      password: password

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password

  h2:
    console:
      enabled: false
      path: /h2-console


logging:
  level:
    org.springframework: debug
    org.springframework.security: debug
    org.springframework.web: debug
    dev.majidhajric.authify: debug
    org.hibernate: info
