server:
  port: 9000

spring:
  application:
    name: authify

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password

  h2:
    console:
      enabled: true  # Enable H2 console (for development purposes)

logging:
  level:
    org.springframework.security: debug
    org.springframework.web: debug
    dev.majidhajric.authify: debug
    org.hibernate: debug
